### ISSUE TITLE
Could one change the encoding in the C++ code to output Norwegian letters?

### ISSUE THREAD

**Issue by MikkoVihtakari** [StoXProject/RstoxData#11]
This would save a lot of processing time in R parts for large files.

**Comment by edvinf** [comment]
This probably relates to issue #15. On platforms where system encoding is UTF-8 at least some of the C++ dependent xml parsing functions output Norwegian letters.

**Comment by iambaim** [comment]
Thanks @MikkoVihtakari and @edvinf for reporting this. However, the solution can be tricky (cf. http://kevinushey.github.io/blog/2018/02/21/string-encoding-and-r/).

As far as I understand, the output from C++ is already in UTF-8. However, non UTF-8 systems (such as Windows) will have trouble processing and displaying it. Perhaps, a simple `Encoding()` the whole data.table as UTF-8 would work?

**Comment by iambaim** [comment]
This is fixed in https://github.com/StoXProject/RstoxData/pull/26 . Can anyone test it to confirm?

**Comment by edvinf** [comment]
Thanks a lot Ibrahim.

I originally produced the issue on Åsmunds computer, and I think it would be best to replicate it there. If Mikko repsonds, that probably sufficient test for now.

Let me know if I should get in touch with Åsmund for testing.

Cheers,
Edvin

**Comment by MikkoVihtakari** [comment]
I get following error message now:

```
dt <- RstoxData::readXmlFile(file)
# Root: missions
# XML namespace: http://www.imr.no/formats/nmdbiotic/v3
# Using XSD: nmdbioticv3.xsd
# Error in readXmlCpp(xmlFilePath, xsdObjects, useXsd) : 
# Index out of bounds: [index='nmdbioticv3.xsd'].
```

Using any file downloaded from @edvinf 's Datasetexplorer / tools. Please check whether you get a similar error. Might be caused due to package installation problems on my computer.

**Comment by iambaim** [comment]
Hi @MikkoVihtakari, please ensure you have installed the latest master and restart R after that. The problem with C++ bundled packages is that sometimes you have to reload R after installing new version of the packages.

If it still doesn't work try to load the package first before `readXmlFile(file)`.

**Comment by MikkoVihtakari** [comment]
I am sorry, but I do not have time for this right now. Will check later (maybe next week, if not early next year).

**Comment by MikkoVihtakari** [comment]
Here is what I get while trying to install the tarball:

```
install.packages("~/Downloads/RstoxData_0.6.3.tgz", repos = NULL, type = .Platform$pkgType)
Error in fetch(key) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RstoxData/help/RstoxData.rdb' is corrupt
```

**Comment by iambaim** [comment]
> Here is what I get while trying to install the tarball:
> 
> ```
> install.packages("~/Downloads/RstoxData_0.6.3.tgz", repos = NULL, type = .Platform$pkgType)
> Error in fetch(key) : 
>   lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RstoxData/help/RstoxData.rdb' is corrupt
> ```
You need to restart your R session before installing the package if the above happens

**Comment by MikkoVihtakari** [comment]
Version 0.6.1 works as expected (also installation from a tarball). Versions 0.6.2 and 0.6.3 throw the errors mentioned above. Additionally, I do not manage to compile those versions. Returns:

> Loading RstoxData
> Error in getDLLRegisteredRoutines.DLLInfo(dll, addNames = FALSE) : 
>   must specify DLL via a “DLLInfo” object. See getLoadedDLLs()
> Calls: suppressPackageStartupMessages ... assignNativeRoutines -> getDLLRegisteredRoutines.DLLInfo
> Execution halted

I work on:

> R version 3.6.1 (2019-07-05)
> Platform: x86_64-apple-darwin15.6.0 (64-bit)
> Running under: macOS High Sierra 10.13.6
> 
> Matrix products: default
> BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> loaded via a namespace (and not attached):
> [1] compiler_3.6.1 tools_3.6.1

**Comment by MikkoVihtakari** [comment]
Now I got 0.6.3 to work too. Restarted R, compiled from the source tarball with errors, got complaints, restarted R and the complaints stopped. This installation issue is unrelated to the Norwegian character issue. Maybe it comes up later. Good if not. Letters look good now. Thanks, @iambaim! I will revise my processBiotic file functions.

**Comment by iambaim** [comment]
This is great! Good to hear it and thanks for reporting back!
