### ISSUE TITLE
Error using :: notation for RstoxData::StoxBiotic

### ISSUE THREAD

**Issue by edvinf** [StoXProject/RstoxData#117]
I have encountered an issue where I cannot run RstoxData::StoxBiotic without first calling library(RstoxData)

The following example reproduces the problem in a new session:

files <- system.file("testresources","biotic_v3_example.xml", package="RstoxData")
inputdata <- RstoxData::ReadBiotic(files)
StoxBioticData <- RstoxData::StoxBiotic(inputdata)
Error in getStoxKeys(StoxDataType = StoxDataType) : 
  object 'stoxBioticObject' not found

Probably relates to:
https://github.com/StoXProject/RstoxData/issues/18

**Comment by iambaim** [comment]
Thanks, @edvinf . I have prepared a fix in #119 .

**Comment by arnejohannesholmin** [comment]
Closing this as it was fixed in #119.
