### ISSUE TITLE
segfault with ReadLandings

### ISSUE THREAD

**Issue by edvinf** [StoXProject/RstoxData#133]
I attach an example landings-file that gives a segfault when reading on Mac OS (10.13.6):

> l<-RstoxData::ReadLanding("~/landingsets/xml/filtered/2015_sild.xml")

 *** caught segfault ***
address 0x0, cause 'memory not mapped'

Traceback:
 1: readXmlCppStream(xmlFilePath, xsdObjects, useXsd, found[["encoding"]],     verbose)
 2: FUN(X[[i]], ...)
 3: lapply(x, FUN, ...)
 4: lapplyOnCores(FileNames, FUN = RstoxData::readXmlFile, NumberOfCores = 1L)
 5: RstoxData::ReadLanding("~/landingsets/xml/filtered/2015_sild.xml")
[2015sild.zip](https://github.com/StoXProject/RstoxData/files/6134966/2015sild.zip)

**Comment by iambaim** [comment]
Thanks for this!

The error happened because the data contains a namespace:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<l:Landingsdata xmlns:l="http://www.imr.no/formats/landinger/v2">
   <l:Seddellinje Dokumentnummer="800001524256" ...
```

I remember I've coded an optional namespace support in the CPP codes. However, it's turned of by default since it still has some bugs. I'll see what I can do with this.

**Comment by edvinf** [comment]
Thanks. I suppose it would work if we only had a default namespace xmlns="...". A compromise that would cover most of these files would be to check if named namespaces occur in the first few 100 bytes and give an explicit error.

**Comment by iambaim** [comment]
I've pushed a fix. Can you try to read the file with the latest `develop` branch?

**Comment by edvinf** [comment]
Yes. Excellent. Thanks a lot.
