### ISSUE TITLE
Non-unique station key after AddToStoxBiotic()

### ISSUE THREAD

**Issue by yreecht** [StoXProject/RstoxData#164]
Hi,

While trying to load reference fleet data using RstoxData (version 1.2.9), I noticed an undesirable behaviour of the AddToStoxBiotic() function, that prevent further merge of the stoxBiotic tables: the Station table ends up with non-unique Station key (which was not the case before the function call)

Here is a reproducible example:
```r
library(dplyr)
library(RCurl)
library(lubridate)

library(RstoxData)

missionTypes <- c("Referanseflåten-Hav", "Referanseflåten-Kyst")

url <- file.path("http://tomcat7.imr.no/apis/nmdapi/biotic/v3", 2020, "cache")
destfile <- "2020.xml"

ret <- download.file(url, destfile = destfile, mode = "wb", method = "auto")

if (ret != 0) # Alternative method if fails:
{
    f <- CFILE(destfile, mode = "wb")
    curlPerform(url = url, writedata = f@ref)
    close(f)
}

##
biotic <- ReadBiotic(destfile)


bioticStox <- StoxBiotic(biotic)

any(duplicated(bioticStox$Cruise$CruiseKey))
any(duplicated(bioticStox$Station$Station))    # No duplicate in the station key!
sum(duplicated(bioticStox$Station$Station))
sum(duplicated(bioticStox$Sample$Sample))
sum(duplicated(bioticStox$SpeciesCategory$SpeciesCategory))
sum(duplicated(bioticStox$Individual$Individual))

bioticStox <- AddToStoxBiotic(StoxBioticData = bioticStox,
                              BioticData = biotic,
                              VariableNames = c("gearcondition","samplequality","stationtype",
                                                "length","maturationstage","startyear",
                                                "missiontypename", "gear", "stationstarttime",
                                                "stationstoptime", "stationstartdate",
                                                "stationstopdate", "commonname", #"scientificname",
                                                "aphia"))

## Now there are duplicates in the Station key:
any(duplicated(bioticStox$Station$Station))
sum(duplicated(bioticStox$Station$Station))

## Fails !
catchSub <- bioticStox %>%
    FilterStoxBiotic(FilterExpression =
                         list(SpeciesCategory = "grepl(\"steinbit\", commonname)"),
                     FilterUpwards = FALSE) %>%
    FilterStoxBiotic(FilterExpression =
                         list(Cruise =
                                  paste0('missiontypename %in% c("',
                                         paste(c(missionTypes), collapse = "\", \""),
                                         '")')),
                     FilterUpwards = TRUE) %>%
     MergeStoxBiotic("Sample")

## Works...but not sure I am suppressing the right ones (filtering on station DateTime is not enough) !
catchSub <- bioticStox %>%
    FilterStoxBiotic(FilterExpression =
                         list(SpeciesCategory = "grepl(\"steinbit\", commonname)"),
                     FilterUpwards = FALSE) %>%
    FilterStoxBiotic(FilterExpression =
                         list(Cruise =
                                  paste0('missiontypename %in% c("',
                                         paste(c(missionTypes), collapse = "\", \""),
                                         '")'),
                              ## Some station are duplicates
                              Station =
                                  paste0("DateTime == as.POSIXct(paste(stationstartdate, ",
                                         "stationstarttime), tz = \"UTC\", format = \"%Y-%m-%dZ %H:%M:%S\") & ",
                                         "! duplicated(Station)")), # Still some duplicates otherwise
                                                                    # (same starttime but different stoptime or stationtype)
                     FilterUpwards = TRUE) %>%
     MergeStoxBiotic("Sample")
```

**Comment by edvinf** [comment]
I have investigated Yves example a bit, applying the additions one-by-one. Some additions adds additional station rows to StoxBiotic. In particular: "stationtype", "stationstarttime", "stationstoptime", "stationstartdate", and "stationstopdate". These are all mapped from biotic$fishstation to StoxBiotic$Station, while they may in fact be different for each haul, and should probably be mapped to StoxBiotic$Haul. I don't know exactly how the mapping is configured, but based on a prelminary investiagtion of the source code I'd suggest changing the configuration in data-raw/stox-translate-nmdbiotic-*.csv so that all fishstation variables that are not part of the StoxBiotic format is mapped to Haul rather than Station. I will assign to @arnejohannesholmin who perhaps knows this code better.

**Comment by edvinf** [comment]
I will try to clarify the issue a little bit more, and summarize a discussion I had with @arnejohannesholmin today.

nmdbiotic$fishstation corresponds to two levels (tables) of the StoxBiotic hierarchy: Station and Haul. 
- For each unique value of the four mission keys in nmdbiotic and nmdbiotic$fishstation$station there should exist one Station in StoxBiotic. 
- For each unique value of the four mission keys in nmdbiotic and nmdbiotic$fishstation$serialnumber there should exist one Haul in StoxBiotic.
- In addition serialnumbers are unique for nmdbiotic$fishstation in combination with nmdbiotic$mission$startYear, which is one fo the four mission kets in nmdbiotic.

So variables in nmdbiotic$fishstation can always be appended to StoxBiotic$Haul, but appending them to StoxBiotic$Station requires that they are identified by the four mission keys in nmdbiotic and nmdbiotic$fishstation$station, or that some procedure is defined to aggregate or select among them if several values are identified for the same Station. This could be "select first occurance", for instance. Such aggregation functions are implemented for the those variables that are mapped from nmdbiotic$fishstation$station to StoxBiotic$Station by the function 'StoxBiotic', but it is not reasonable to implement them for other variables that may be added by 'AddToStoxBiotic'. 

One solution would be to define all mappings between nmdbiotic$fishstation to StoxBiotic$Haul, except for those that are explicitly handled by the function 'StoxBiotic'.

We need to check if similar concerns apply to the mapping from nmdbiotic$catchsample to StoxBiotic$SpeciesCategory and StoxBiotic$Sample.

**Comment by edvinf** [comment]
Discussed with AJ today. Can be implemented as sketched above, but need to add a check that variables added are not repated on any level i the data object they are added to.

**Comment by edvinf** [comment]
Discussed with AJH and EJ consequences for backwardscompatibility when variables are mapped to a different level. Decided to expose user option where the user can specify whether haul-variables should:
1. Be done to station, implying that only first haul is used. (default option)
2. Be done to haul.

**Comment by edvinf** [comment]
I have tested Yves example on a previously downloaded 2020-file. It seems to work now, without introducing duplicates.
