### ISSUE TITLE
Problems reading special characters on directories (i.e. "å")

### ISSUE THREAD

**Issue by Hectorar1** [StoXProject/RstoxData#223]
When reading an XML file with directory name including the letter "å", the program will crash. Example:

example<- RstoxData::readXmlFile("C:/Users/Desktop/Blålange/Data_XML/biotic_year_2021_species_164761(1).xml")

The following message appears: 
Error in readXmlCppStream(xmlFilePath, xsdObjects, useXsd, found[["encoding"]],  : 
  c++ exception (unknown reason)

The problem gets easyly solved by changing the letter "å" in the directory (in this case, it was changed to "aa")
C:/Users/a37358/Desktop/Blaalange/Data_XML/biotic_year_2021_species_164761(1).xml"

**Comment by edvinf** [comment]
Thank you for reporting. A similar issue has been solved recently (https://github.com/StoXProject/RstoxData/issues/154). If you are using a version older than RstoxData-v1.5.10, would it be possible to test with an updated version?

If you are using RstoxData-v1.5.10 or newer, we would much like to know some details about your configuration:
- the exact RstoxData-version
- the version of R
- the operating system
