### ISSUE TITLE
Make readXmlFile function silent or add an argument to allow running it silent

### ISSUE THREAD

**Issue by MikkoVihtakari** [StoXProject/RstoxData#30]
Currently the `readXmlFile` function prints text when run it:

```
# RstoxUtils package: https://github.com/MikkoVihtakari/RstoxUtils
xml.example <- system.file("extdata", "example.xml", package = "RstoxUtils")
standard.format <- RstoxData::readXmlFile(xml.example)
[1] "Try to use XML namespace"
Parsing XML: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/RstoxUtils/extdata/example.xml
Root: missions
XML namespace: nmdbioticv3
Using XSD: nmdbioticv3.xsd
```

It is not possible to silence the function using the common `suppress*` silencer family, but `capture.output` works. Could it be possible to either remove the texts printed by the function altogether or add an argument that makes the function silent? There are many applications where such messages are not desired and making a `capture.output` hook every time seems unnecessarily complicated.

**Comment by iambaim** [comment]
Thanks, a very good suggestion.

I have implemented a parameter named `verbose` for `readXmlFile` function in 636f8c756f43d4ecd2ab697a7b345c4f88dfd93c.

**Comment by MikkoVihtakari** [comment]
Thanks @iambaim!
