### ISSUE TITLE
datatype for agedeterminationid

### ISSUE THREAD

**Issue by edvinf** [StoXProject/RstoxData#31]
When reading biotic 3 files, the column agedeterminationid is parsed as character, although xsd specifies xs:integer.

**Comment by iambaim** [comment]
Thanks for this. Actually, not only the `agedeterminationid` column that is broken, many other columns are still wrongly parsed as character :)

I have made a fix for this in 2139232fd5bb9f9e67c0d8baa4d4ffb5b89f6869. However, this fix breaks `StoxAcoustic` function. Therefore, I have made an additional fix (2f4438e72fdeabff8267e5fcba68d6f824107068).

**Comment by edvinf** [comment]
Thanks a lot. I have tested it with the code that revealed the issue. It works fine now.
