### ISSUE TITLE
Installing Windows binary under R 4.0.0 (also applies for 3.5.3)

### ISSUE THREAD

**Issue by MikkoVihtakari** [StoXProject/RstoxData#75]
When installing the binary of the package under Windows, one of my colleagues gets an error:

![image](https://user-images.githubusercontent.com/4095204/81914451-9c3a6e80-95d1-11ea-8fc1-7685ea9972b6.png)

I have not tried to reproduce this error. Is the binary creation corrupted somehow?

**Comment by iambaim** [comment]
Hi @MikkoVihtakari,

Try to install using this command instead:
`install.packages("RstoxData", repo="https://stoxproject.github.io/repo")`

FYI, we don't have any binaries for R version 3.5 anymore, only for version 3.6 and 4.0.

**Comment by MikkoVihtakari** [comment]
My colleague reports that your suggestion solved the issue.
